### ISSUE TITLE
watcharr.py", line 75, in __del__

### ISSUE THREAD

**Issue by daktak** [airdogvan/watcharr_kodi#1]
Kodi v21

`2024-08-04 14:33:55.328 T:27931    info <general>: Skipped 1 duplicate messages..
2024-08-04 14:33:55.328 T:27931   error <general>: Exception ignored in:
2024-08-04 14:33:55.328 T:27931   error <general>: <function WatchArr.__del__ at 0x7f729ff51940>
2024-08-04 14:33:55.328 T:27931   error <general>:

2024-08-04 14:33:55.328 T:27931   error <general>: Traceback (most recent call last):

2024-08-04 14:33:55.328 T:27931   error <general>:   File "/home/mythtv/.kodi/addons/script.watcharr/watcharr.py", line 75, in __del__

2024-08-04 14:33:55.329 T:27931   error <general>:
2024-08-04 14:33:55.329 T:27931   error <general>: self.req.close()
2024-08-04 14:33:55.329 T:27931   error <general>:

2024-08-04 14:33:55.329 T:27931   error <general>:
2024-08-04 14:33:55.329 T:27931    info <general>: Skipped 3 duplicate messages..
2024-08-04 14:33:55.329 T:27931   error <general>: ^
2024-08-04 14:33:55.329 T:27931    info <general>: Skipped 7 duplicate messages..
2024-08-04 14:33:55.329 T:27931   error <general>:

2024-08-04 14:33:55.329 T:27931   error <general>: AttributeError
2024-08-04 14:33:55.329 T:27931   error <general>: :
2024-08-04 14:33:55.329 T:27931   error <general>: 'WatchArr' object has no attribute 'req'
2024-08-04 14:33:55.330 T:27931   error <general>:

2024-08-04 14:33:55.335 T:27931   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: WatchArr.__init__() missing 1 required positional argument: 'watcharr_url'
                                                   Traceback (most recent call last):
                                                     File "/home/mythtv/.kodi/addons/script.watcharr/default.py", line 305, in <module>
                                                       player = MEPlayer()
                                                                ^^^^^^^^^^
                                                     File "/home/mythtv/.kodi/addons/script.watcharr/default.py", line 68, in __init__
                                                       self._reset()
                                                     File "/home/mythtv/.kodi/addons/script.watcharr/default.py", line 79, in _reset
                                                       self.mwarr: WatchArr = MEPlayer.initWatchArr()
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/mythtv/.kodi/addons/script.watcharr/default.py", line 106, in initWatchArr
                                                       return WatchArr("", "")
                                                              ^^^^^^^^^^^^^^^^
                                                   TypeError: WatchArr.__init__() missing 1 required positional argument: 'watcharr_url'
                                                   -->End of Python script error report<--
`

**Comment by airdogvan** [comment]
thanks for including the log.
The error was raised because you forgot to enter your Watcharr's instance URL.
I will correct the code to add error message for the user.

**Comment by daktak** [comment]
Hmm I thought I did, maybe that was before setting it

So now I get the logged in notification, but it does not seem to scrobble

Only entry I could find was

`2024-08-05 16:44:54.238 T:2517     info <general>: CAddonMgr::FindAddon: script.watcharr v.7.0.0 installed
2024-08-05 16:45:16.421 T:2517     info <general>: CServiceAddonManager: failed to stop script.watcharr (may have ended)`

**Comment by airdogvan** [comment]
I have to admit that this one has me scratching my head, never seen this one before.  
Can I ask which version of Kodi you're running?
Also, in the ./kodi/addons/script.watcharr folder there should be a debug.txt file.  Could you let me know what's in there?  Be careful as this file contains your userid and password, so blank those out when you paste.
Thanks

**Comment by daktak** [comment]
Thanks.. Yeah do you know if there is any log in Watcharr itself we can check if it ever reached out to scrobble? It looks like it never did reach out.

I'm using Kodi v21 Omega

hmm localhost:3129 is my proxy (i have it set as env http_proxy var)

I now suspect my proxy, Will debug this first ;-)

```
2024-06-28 14:42:45,820 - logger - DEBUG - Start of the file
2024-06-28 14:42:48,277 - logger - DEBUG - And here we go again!
2024-06-28 15:11:46,172 - logger - DEBUG - Start of the file
2024-08-05 16:44:56,063 - logger - DEBUG - Start of the file
2024-08-05 16:44:56,067 - __main__ - DEBUG - Settings = user, pass, http://192.168.1.10:3080/api
2024-08-05 16:44:56,084 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:3129
2024-08-05 16:44:57,847 - urllib3.connectionpool - DEBUG - http://localhost:3129 "POST http://192.168.1.10:3080/api/auth/ HTTP/1.1" 200 193
2024-08-05 16:44:57,985 - urllib3.connectionpool - DEBUG - http://localhost:3129 "GET http://192.168.1.10:3080/api/watched HTTP/1.1" 200 None
2024-08-05 16:44:58,023 - __main__ - DEBUG - mwarrPlayer - account is logged successfully.
2024-08-05 16:44:58,024 - __main__ - DEBUG - [Watcharr] - Version: .7.0.0 Started
2024-08-05 16:45:19,774 - logger - DEBUG - Start of the file
2024-08-05 16:45:19,780 - __main__ - DEBUG - Settings = user, pass, http://192.168.1.10:3080/api
2024-08-05 16:45:19,801 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:3129
2024-08-05 16:45:22,040 - urllib3.connectionpool - DEBUG - http://localhost:3129 "POST http://192.168.1.10:3080/api/auth/ HTTP/1.1" 200 193
2024-08-05 16:45:22,225 - urllib3.connectionpool - DEBUG - http://localhost:3129 "GET http://192.168.1.10:3080/api/watched HTTP/1.1" 200 None
2024-08-05 16:45:22,259 - __main__ - DEBUG - mwarrPlayer - account is logged successfully.
2024-08-05 16:45:22,260 - __main__ - DEBUG - [Watcharr] - Version: .7.0.0 Started
```

**Comment by airdogvan** [comment]
It's not your proxy.  Hadn't used Kodi in a while and tried it today: same result as you.  Doesn't scrobble at all.  Not sure what's going on, didn't change a comma in the code and that code scrobbled a lot of episodes, now nothing.

Have to do some debugging.  I ask for your patience as Kodi debugging is not easy and it's a long process.  Will get back as soon as I have news.

**Comment by daktak** [comment]
Yeah must be intermittent, just scrobbled an episode today successfully

**Comment by airdogvan** [comment]
OK, found the problem.  In latest version I added a method (not mine but from kodi base)  that is behaving unreliably.  Didn't really need it.  Please uninstall .7.0.0, restart Kodi and  install .7.0.1, it should take care of the problem.  

Please note when you uninstall in Kodi, it will ask you if you also want to delete the associated settings.  Just answer "no".
